### PR TITLE
enhancement - chrome - consider synchronizing user data across computers

### PR DESCRIPTION
**Pull request by micheleb**
for users accessing facebook from multiple computers (like myself), it's a little annoying having to post the pairing message on your fb wall multiple times, one for each computer.

Since the extension is already being automagically sync'ed by Chrome across computers, it'd be nice to sync user data as well.

According to [this dev page][1], it looks like all that's needed is the little change I made here, as long as the user is using a single fb account, that is. Please **note**: I haven't tested it.

[1]: https://developer.chrome.com/extensions/storage

### CODE REVIEW

**Comment by vrde** [comment]
Thanks! It works, and it was like this for a while, then I [changed it to `local` to be compatible with Firefox](https://github.com/tracking-exposed/web-extension/commit/57b188a5c96c88b7185a17ec97f42cd0fd4f012b#diff-dc9bba4cabd59b42b61e6b82e19b833aL5).

There is still value in using `sync` if you are on Chrome (it's also the most used browser out there).
We can support both with something like this probably:

```javascript
const backend = chrome.storage.sync || chrome.storage.local;
```

**Comment by micheleb** [comment]
wow, I had no idea that a Firefox extension and a Chrome extension could even share the exact same codebase and both work!

**Comment by vrde** [comment]
> wow, I had no idea that a Firefox extension and a Chrome extension could even share the exact same codebase and both work!

cool, right? :dancer: 

Anyway before merging this we should add a script to migrate users from `chrome.backend.local` to `chrome.backend.sync` :fearful:. I have some ideas if you want to do it.

**Comment by vrde** [comment]
We have a `1-n` relationship between a user and public keys, so for now synchronizing `storage`s is not a priority.

**Pull request closed without merging**
