### PR TITLE
Add visual feedback to posts in newsfeed

### PR DESCRIPTION
**Pull request by vrde**
This PR makes explicit which posts the extension collects and which posts is ignored. I've added also a "report" button. Right now it points to our email address `support@tracking.exposed`. Later we can improve it and add more options.

## Public post [updated]
image

## Private post [updated]
image

### CODE REVIEW

**Comment by micheleb** [comment]
it'd be nice if the notification had a little tracking-exposed logo somewhere, so as a user I could tell who that message is coming from (as in, from the chrome extension, as opposed to from facebook itself, which might make me feel a little uneasy about it)

**Comment by vrde** [comment]
> it'd be nice if the notification had a little tracking-exposed logo somewhere, so as a user I could tell who that message is coming from (as in, from the chrome extension, as opposed to from facebook itself, which might make me feel a little uneasy about it)

Done! (Screenshots updated

**Comment by vecna** [comment]
I'm skeptical for the size, for the lack of localisation at the moment and for the interaction the users can have. Is a good beginning to enhance exchanges between us and the user and the explicit communication of what is being shared.

I'm ok in begin with this, but if we can set a list of next task to reach some improvement, that's might be even better. I'm thinking of:

1. "report" is the action we want to trigger, a bug report or a will report ? if is a bug, is about the parsing, if is about the parsing is due to the lack of language support, so we've to drive the user on the community page and tell us how the "Public" looks like in their language. if is a report, we've to keep track of the postId, so we can interact with the system (or even automatize) a post removal 
2. the size: seems to big? will became annoying? will make feel users uncomfortable? the best improvement for me might be: 
- a way to close such banner permanently, communicated server side, and only if the user exert some advanced option in the page, we communicate back to the extension to display it again. This has sense if the banner is only informative. if is part of the interaction, (point 3) don't apply
- a single line communication, reduce the space used, maybe disappear after 1 second with a fadeout, is an usability/communication issue I can feel but I can't solve
3. the interaction: that can be a powerful tool to lead the user as immediate action, for example: a link to the realitycheck of that post, a link where the metadata of the same post are extracted, or a link to share with others. the banner can even contain information received back from the server. this is an opportunity we can think about it
4. the role: if the interaction with fb.tr.ex can pass through that banner, can we remove the logo? doesn't the page looking "monopolized" by the project, being so recurrent?

**Comment by vecna** [comment]
Additional thing for this PR:
  * comeback to use collector.facebook.tracking.exposed as delivery point. The SSL problem has been solved, having the hostname separate is strategical in case we've to change boxes, split the services between collection and visualization, and if we move the web in a CDN

**Comment by vecna** [comment]
has to be tested in the look & feel in:
- when the post receive an interaction, and you'll see appear on the bottom right
- when you do onmouseover recent activities, and they get render

**Comment by vecna** [comment]
Note: When errors are returned by a server, instead of `{ 'status': 'OK' }` they contains:

```
                error = {
                    'status': 'error',
                    'source': 'exception',
                    'details': error
                };
```

This might lead to a dedicated feedback on the UI

**Comment by vrde** [comment]
@vecna thanks for your feedback. There are many ideas we can tackle in different PRs.

> "report" is the action we want to trigger, a bug report or a will report ? if is a bug, is about the parsing, if is about the parsing is due to the lack of language support, so we've to drive the user on the community page and tell us how the "Public" looks like in their language. if is a report, we've to keep track of the postId, so we can interact with the system (or even automatize) a post removal

If we have false positives, we need to give the user a way to report this behavior. Right now the CTA is just "email us". This will be improved in the future. See #14

> the size: seems to big? will became annoying? will make feel users uncomfortable? the best improvement for me might be:
> - a way to close such banner permanently, communicated server side, and only if the user exert some advanced option in the page, we communicate back to the extension to display it again. This has sense if the banner is only informative. if is part of the interaction, (point 3) don't apply
> - a single line communication, reduce the space used, maybe disappear after 1 second with a fadeout, is an usability/communication issue I can feel but I can't solve

I agree to add a feature to make it concealable, see #16. Usually I don't make assumptions on users. I think that **being explicit** is the best first step, because you don't make assumptions on what the user knows. If we don't make it explicit, then the user might not understand what we do with their data.

The main reason to add the logo and title in the header of the infobox is https://github.com/tracking-exposed/web-extension/pull/7#issuecomment-267848391. We need to give users **context**, at least for the first steps.

> the interaction: that can be a powerful tool to lead the user as immediate action, for example: a link to the realitycheck of that post, a link where the metadata of the same post are extracted, or a link to share with others. the banner can even contain information received back from the server. this is an opportunity we can think about it

sure thing, as soon as the visualizations are back we can add this link. We can even display some of the info directly in the FB page if we want :smiling_imp: 

> the role: if the interaction with fb.tr.ex can pass through that banner, can we remove the logo? doesn't the page looking "monopolized" by the project, being so recurrent?

I think #11 makes the need of the button redundant. I just created #15 to solve this.

> comeback to use collector.facebook.tracking.exposed as delivery point. The SSL problem has been solved, having the hostname separate is strategical in case we've to change boxes, split the services between collection and visualization, and if we move the web in a CDN

Moved and solved in another PR to keep the scope of this one tight. See #13.

**Comment by vrde** [comment]
@vecna TL;DR I just added #16 to https://github.com/tracking-exposed/web-extension/milestone/1, I think this is a good compromise.

**Pull request merged**
