### PR TITLE
remove js and css responsible for fbtrex button in bottom left corner

### PR DESCRIPTION
**Pull request by vdzimwasha**
Here's a fix for #15. I've removed the code in the app.js file and the app.scss file. 

Thanks for letting me have a shot at this pull request! Let me know if anything else needs doing.

### CODE REVIEW

**Comment by vecna** [comment]
@vdzimwasha <3

**Comment by vdzimwasha** [comment]
Hey!  I suspected I'd have to remove those but didn't want to touch them just encase they were used elsewhere. I've removed them now.  

Ohhh didn't know you could do that. Thanks for the pro-tip.

**Comment by vrde** [comment]
> Hey! I suspected I'd have to remove those but didn't want to touch them just encase they were used elsewhere. I've removed them now.

no problem! Usually I use [`ag`](https://github.com/ggreer/the_silver_searcher) to check where a file or class is used in the codebase.

Since the file `src/components/startButton.js` is gone, we need to remove also its styles. The component were using the class `fbtrex--main-button`. If you use `ag`, you'll see something like:
```
 ~/r/t/web-extension git:(vdzimwasha-master) ➜ ag .fbtrex--main-button
styles/buttons.scss
1:.fbtrex--main-button {
15:.fbtrex--main-button:hover {
```

Basically, `ag` is telling us that the class `fbtrex--main-button` is defined in the file `styles/buttons.scss`. Since that file contains only this styling, we can safely remove the file entirely.

After this last change we are ready to merge! :dancer: 

> Ohhh didn't know you could do that. Thanks for the pro-tip.

Yep! It's really helpful. GitHub will also add a link from the issue #15 to this PR #17:
image

**Comment by vdzimwasha** [comment]
> Usually I use ag to check where a file or class is used in the codebase.
I'd never heard of ag or even thought you could do that until this very moment. I'll add that to my list of things to include in my set-up. 

So that file should be gone now and fingers crossed so should everything related to the button. I did notice there were image files in the build folder but I don't have to touch those do I?

**Comment by vrde** [comment]
> So that file should be gone now and fingers crossed so should everything related to the button. I did notice there were image files in the build folder but I don't have to touch those do I?

I think we can keep the asset for now! Thanks for your PR!

**Pull request merged**
